urls.py
__author__ = 'ismailsunni'

from django.conf.urls import patterns, url

from geosafe.views import metasearch
from geosafe.views.analysis import (
    AnalysisListView,
    AnalysisCreateView,
    AnalysisDetailView,
    layer_tiles,
    layer_metadata,
    layer_keywords,
    layer_archive,
    layer_list, rerun_analysis,
    analysis_json, toggle_analysis_saved, download_report, layer_panel,
    analysis_summary, cancel_analysis, validate_analysis_extent,
    impact_json, layer_geojson)

urlpatterns = patterns(
    '',
    url(
        r'^analysis/create(?:/(?P<pk>\d*))?$',
        AnalysisCreateView.as_view(),
        name='analysis-create'
    ),
    url(
        r'^analysis/(?:/user/(?P<user>\d*))?$',
        AnalysisListView.as_view(),
        name='analysis-list'
    ),
    url(
        r'^analysis/(?P<pk>\d+)$',
        AnalysisDetailView.as_view(),
        name='analysis-detail'
    ),
    url(
        r'^analysis/layer-geojson$',
        layer_geojson,
        name='layer-geojson'
    ),
    url(
        r'^analysis/layer-tiles$',
        layer_tiles,
        name='layer-tiles'
    ),
    url(
        r'^analysis/layer-metadata/(?P<layer_id>\d+)',
        layer_metadata,
        name='layer-metadata'
    ),
    url(
        r'^analysis/layer-keywords$',
        layer_keywords,
        name='layer-keywords'
    ),
    url(
        r'^analysis/layer-archive/(?P<layer_id>\d+)',
        layer_archive,
        name='layer-archive'
    ),
    url(
        r'^analysis/layer-list/'
        r'(?P<layer_purpose>(hazard|exposure|aggregation|impact))'
        r'(?:/(?P<layer_category>\w*))?'
        r'(?:/(?P<bbox>[,.\d-]*))?',
        layer_list,
        name='layer-list'
    ),
    url(
        r'^analysis/layer-panel'
        r'(?:/(?P<bbox>[\[\] ,.\d-]*))?',
        layer_panel,
        name='layer-panel'
    ),
    url(
        r'^analysis/extent/validation/',
        validate_analysis_extent,
        name='validate-analysis-extent'
    ),
    url(
        r'^analysis/extent/calculate/',
        validate_analysis_extent,
        name='calculate-area'
    ),
    url(
        r'^analysis/rerun/'
        r'(?P<analysis_id>\d+)',
        rerun_analysis,
        name='rerun-analysis'
    ),
    url(
        r'^analysis/cancel/'
        r'(?P<analysis_id>\d+)',
        cancel_analysis,
        name='cancel-analysis'
    ),
    url(
        r'^analysis/check/'
        r'(?P<analysis_id>\d+)',
        analysis_json,
        name='check-analysis'
    ),
    url(
        r'^analysis/check-impact/'
        r'(?P<impact_id>[-\d]+)',
        impact_json,
        name='check-impact'
    ),
    url(
        r'^analysis/toggle-saved/'
        r'(?P<analysis_id>[-\d]+)',
        toggle_analysis_saved,
        name='toggle-analysis-saved'
    ),
    url(
        r'^analysis/report/'
        r'(?P<analysis_id>[-\d]+)/'
        r'(?P<data_type>(map|table|reports|all))',
        download_report,
        name='download-report'
    ),
    url(
        r'^analysis/summary/'
        r'(?P<impact_id>[-\d]+)/',
        analysis_summary,
        name='analysis-summary'
    ),

    # Metasearch
    url(
        r'^metasearch/$',
        metasearch.index,
        name='metasearch'
    ),
    url(
        r'^metasearch/csw_ajax$',
        metasearch.csw_ajax,
        name='metasearch_csw_ajax'
    ),
    url(
        r'^metasearch/add_layer$',
        metasearch.add_layer,
        name='metasearch_add_layer'
    ),
    url(
        r'^metasearch/add_layer_dialog',
        metasearch.show_add_layer_dialog,
        name='metasearch_add_layer_dialog'
    ),
    url(
        r'^metasearch/show_metadata',
        metasearch.show_metadata,
        name='metasearch_show_metadata'
    ),

    url(
        r'^metasearch/wfs_proxy',
        metasearch.wfs_proxy,
        name='metasearch_wfs_proxy'
    ),
)

forms.py
# coding=utf-8
import logging

from django import forms
from django.forms import models
from django.utils.translation import ugettext as _

from geonode.layers.models import Layer
from geonode.people.models import Profile
from geosafe.models import Analysis

__author__ = 'ismailsunni'

LOGGER = logging.getLogger(__name__)


class AnalysisCreationForm(models.ModelForm):
    """A form for creating an event."""

    class Meta:
        model = Analysis
        fields = (
            'user_title',
            'user_extent',
            'exposure_layer',
            'hazard_layer',
            'aggregation_layer',
            'aggregation_filter',
            'language_code',
            'extent_option',
            'keep',
        )

    user_title = forms.CharField(
        label='Analysis Title',
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': _('Default title generated')})
    )

    user_extent = forms.CharField(
        label='Analysis Extent',
        required=False,
    )

    exposure_layer = forms.ModelChoiceField(
        label='Exposure Layer',
        required=True,
        queryset=Layer.objects.filter(
            inasafe_metadata__layer_purpose='exposure'),
        widget=forms.Select(
            attrs={'class': 'form-control'})
    )

    hazard_layer = forms.ModelChoiceField(
        label='Hazard Layer',
        required=True,
        queryset=Layer.objects.filter(
            inasafe_metadata__layer_purpose='hazard'),
        widget=forms.Select(
            attrs={'class': 'form-control'})
    )

    aggregation_layer = forms.ModelChoiceField(
        label='Aggregation Layer',
        required=False,
        queryset=Layer.objects.filter(
            inasafe_metadata__layer_purpose='aggregation'),
        widget=forms.Select(
            attrs={'class': 'form-control'})
    )

    aggregation_filter = forms.CharField(
        required=False,
        widget=forms.HiddenInput()
    )
    # Filter format:
    # This field should contain JSON object with the following format:
    #     {
    #         'property_name': <the name of the property to filter>
    #         'values': <list of values for this property>
    #     }
    #
    # Example:
    #
    #     {
    #         'property_name': 'area_name',
    #         'values': ['area 1', 'area 2', 'area 3']
    #     }

    language_code = forms.CharField(
        required=False,
        widget=forms.HiddenInput()
    )

    keep = forms.BooleanField(
        label='Save Analysis',
        required=False,
    )

    @staticmethod
    def exposure_choice_queryset():
        return Layer.objects.filter(
            inasafe_metadata__layer_purpose='exposure')

    @staticmethod
    def hazard_choice_queryset():
        return Layer.objects.filter(
            inasafe_metadata__layer_purpose='hazard')

    @staticmethod
    def aggregation_choice_queryset():
        return Layer.objects.filter(
            inasafe_metadata__layer_purpose='aggregation')

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.language_code = kwargs.pop('language_code', None)
        exposure_layer = kwargs.pop('exposure_layer', None)
        hazard_layer = kwargs.pop('hazard_layer', None)
        aggregation_layer = kwargs.pop('aggregation_layer', None)
        super(AnalysisCreationForm, self).__init__(*args, **kwargs)
        if exposure_layer:
            self.fields['exposure_layer'].queryset = exposure_layer
        else:
            self.fields['exposure_layer'].queryset = \
                self.exposure_choice_queryset()
        if hazard_layer:
            self.fields['hazard_layer'].queryset = hazard_layer
        else:
            self.fields['hazard_layer'].queryset = \
                self.hazard_choice_queryset()
        if aggregation_layer:
            self.fields['aggregation_layer'].queryset = aggregation_layer
        else:
            self.fields['aggregation_layer'].queryset = \
                self.aggregation_choice_queryset()

    def save(self, commit=True):
        instance = super(AnalysisCreationForm, self).save(commit=False)
        if self.language_code:
            instance.language_code = self.language_code
        if self.user.username:
            instance.user = self.user
        else:
            instance.user = Profile.objects.get(username='AnonymousUser')
        # validate aggregation filter
        if instance.aggregation_layer:
            if not instance.aggregation_filter:
                # Standardize to empty value
                instance.aggregation_filter = None
        instance.save()
        return instance


class MetaSearchForm(forms.Form):

    class Meta:
        fields = (
            'csw_url',
            'keywords',
            'user',
            'password',
        )

    csw_url = forms.CharField(
        label='CSW URL',
        help_text='URL to CSW endpoint',
        required=True)
    keywords = forms.CharField(
        help_text='Keywords to include in the search',
        required=False)
    user = forms.CharField(
        help_text='User to connect to CSW Endpoint',
        required=False)
    password = forms.CharField(
        help_text='Password to connect to CSW Endpoint',
        required=False,
        widget=forms.PasswordInput(render_value=True))

templates/geosafe/metasearch/modal/add_layer.html
{% load bootstrap_tags %}
{% load staticfiles %}
<div class="modal fade" id="add-layer" tabindex="-1" role="dialog" aria-labelledby="Add Layer">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i class="fa fa-times-circle-o"></i></button>
                    <h4 class="modal-title" id="add_confirmation_label">
                    <img class="glyphicon" src="{% static 'geosafe/img/inasafe-icon.png' %}" ></img>
                    Add Layer
                </h4>
            </div>
            <div class="modal-body">
                <form id="add-layer-form" action="{% url 'geosafe:metasearch_add_layer' %}" method="post">
                    <input type="hidden" name="user" />
                    <input type="hidden" name="password" />
                    <input type="hidden" name="identifier" value="{{ record.identifier }}" />
                    <input type="hidden" name="service_id" value="{{ record.service_id }}" />
                    <input type="hidden" name="service_version" value="{{ record.service_version }}" />
                    <div class="form-group">
                        <label>Title</label>
                        <input id="confirm_layer_title" type="text" disabled class="form-control" value="{{ record.title }}"/>
                    </div>
                    <div class="form-group">
                        <label>Abstract</label>
                        <input id="confirm_layer_abstract" type="text" disabled class="form-control" value="{{ record.abstract }}"/>
                    </div>
                    <div class="form-group">
                        <label>Endpoint</label>
                        <input id="confirm_layer_endpoint" name="endpoint" type="text" disabled class="form-control" value="{{ record.endpoint }}"/>
                    </div>
                    <div class="form-group">
                        <label>Endpoint Type</label>
                        <input id="confirm_layer_type" name="type" type="text" disabled class="form-control" value="{{ record.type }}"/>
                    </div>
                    <div class="form-group">
                        <label>Extent</label>
                        <div style="width: 100%">
                            <div class="btn-group" data-toggle="buttons">
                                <span class="btn btn-primary active">
                                    <input type="radio" name="extent" checked value="map"/>
                                    Use Map
                                </span>
                                <span class="btn btn-primary">
                                    <input type="radio" name="extent" value="input"/>
                                    Use Input
                                </span>
                            </div>
                            <input id="confirm_reset_extent" type="button" class="btn btn-primary" value="Reset Extent" style="margin-left: 50px;" />
                        </div>
                        <div id="map" style="height: 500px">
                        </div>
                        <div id="extent-input">
                            <label for="confirm_minx">Minx</label>
                            <input id="confirm_minx" name="minx" type="number" class="form-control">
                            <label for="confirm_miny">Miny</label>
                            <input id="confirm_miny" name="miny" type="number" class="form-control">
                            <label for="confirm_maxx">Maxx</label>
                            <input id="confirm_maxx" name="maxx" type="number" class="form-control">
                            <label for="confirm_maxy">Maxy</label>
                            <input id="confirm_maxy" name="maxy" type="number" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-primary" type="submit" value="Add Layer" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var map;
    $(document).ready(function(){
        var OpenMapSurfer_Roads = L.tileLayer('http://korona.geog.uni-heidelberg.de/tiles/roads/x={x}&y={y}&z={z}', {
            noWrap: true,
            attribution: 'Imagery from <a href="http://giscience.uni-hd.de/">GIScience Research Group @ University of Heidelberg</a> &mdash; Map data &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        });
        map = L.map('map', {
            layers: [OpenMapSurfer_Roads]
        });

        {% if record.type.lower == 'wfs' %}
            var root_url = '{{ record.endpoint }}';
            var default_param = {
                service: 'WFS',
                version: '1.0.0',
                request: 'GetFeature',
                typeName: '{{ record.service_id }}',
                maxFeatures: 200,
                outputFormat: 'text/javascript',
                format_options: 'callback: getJson',
                srsName:'EPSG:4326'
            };
            var parameters = L.Util.extend(default_param);
            $.ajax({
                jsonp: false,
                url: root_url + L.Util.getParamString(parameters),
                dataType: 'jsonp',
                jsonpCallback: 'getJson',
                success: handleJson
            });
            var group = new L.featureGroup().addTo(map);
            var geojsonlayer;
            function handleJson(data) {
                geojsonlayer=L.geoJson(data, {
                    onEachFeature: function (feature, my_Layer) {
                            my_Layer.bindPopup("str.1: "+feature.properties.str1+"<br />cat: "+feature.properties.cat);
                        },
                    pointToLayer: function (feature, latlng) {
                        return L.circleMarker(latlng);
                    }
                }).addTo(group);
                map.fitBounds(group.getBounds());
            }

{#            var params = {#}
{#                'typename': '{{ record.service_id }}',#}
{#                'endpoint': '{{ record.endpoint }}'#}
{#            };#}
{#            var group = new L.featureGroup().addTo(map);#}
{#            var geojsonlayer;#}
{#            $.get('{% url "geosafe:metasearch_wfs_proxy" %}', params, function(data){#}
{#                if(data){#}
{#                    geojsonlayer = L.geoJson(data, {#}
{#                        onEachFeature: function(feature, layer){#}
{#                            layer.bindPopup("properties: "+feature.properties);#}
{#                        },#}
{#                        pointToLayer: function (feature, latlng) {#}
{#                            return L.circleMarker(latlng);#}
{#                        }#}
{#                    }).addTo(group);#}
{#                    map.fitBounds(group.getBounds());#}
{#                }#}
{#            });#}

        {% elif record.type.lower == 'wms' or record.type.lower == 'wcs' %}
            var endpoint = '{{ record.endpoint }}';
            endpoint = endpoint.replace('/wcs', '/wms');

            var tilelayer = L.tileLayer.wms(endpoint,{
                layers: '{{ record.service_id }}'
            }).addTo(map);
        {% endif %}
        {# update extent view #}
        var extent_change_map = function (event) {
            var bounds = map.getBounds();
            $("#confirm_minx").val(bounds.getWest());
            $("#confirm_miny").val(bounds.getSouth());
            $("#confirm_maxx").val(bounds.getEast());
            $("#confirm_maxy").val(bounds.getNorth());
        };

        var extent_change_input = function(event){
            var get_number = function(id){
                return parseFloat($(id).val());
            };
            var bbox = [
                    [get_number("#confirm_miny"), get_number("#confirm_minx")],
                    [get_number("#confirm_maxy"), get_number("#confirm_maxx")]
            ];
            map.fitBounds(bbox);
        };

        {# check active extent input #}
        $("input[name=extent]").change(function(event){
            var val = $(this).val();
            if(val == "map"){
                $("#extent-input input").prop('disabled', true);

                map.on('moveend', extent_change_map);
                extent_change_map();
                $("#extent-input input").off('change', extent_change_input);

                map.dragging.enable();
                map.touchZoom.enable();
                map.doubleClickZoom.enable();
                map.scrollWheelZoom.enable();
                map.boxZoom.enable();
                map.keyboard.enable();
                if (map.tap) map.tap.enable();
                $("#map").get(0).style.cursor='';
            }
            else if(val == "input"){
                $("#extent-input input").prop('disabled', false);

                map.off('moveend', extent_change_map);
                $("#extent-input input").on('change', extent_change_input);
                extent_change_input();

                map.dragging.disable();
                map.touchZoom.disable();
                map.doubleClickZoom.disable();
                map.scrollWheelZoom.disable();
                map.boxZoom.disable();
                map.keyboard.disable();
                if (map.tap) map.tap.disable();
                $("#map").get(0).style.cursor='not-allowed';
            }
        });

        var resetExtent = function(event){
            var bbox = [
                [{{ record.bbox.miny }}, {{ record.bbox.minx }}],
                [{{ record.bbox.maxy }}, {{ record.bbox.maxx }}]
            ];
            map.fitBounds(bbox);
        };

        $("#confirm_reset_extent").click(resetExtent);

        $("#add-layer-form").submit(function(event){
            var $form = $(this);
            var data = $form.serializeObject();
            data.endpoint = $("input[name=endpoint]", $form).val();
            data.type = $("input[name=type]", $form).val();
            data.minx = $("input[name=minx]", $form).val();
            data.maxx = $("input[name=maxx]", $form).val();
            data.miny = $("input[name=miny]", $form).val();
            data.maxy = $("input[name=maxy]", $form).val();
            $.ajax({
                type: $form.attr('method'),
                url: $form.attr('action'),
                data: data,
                success: function (data) {
                    if(data){
                        console.log(data);
                        if(data.success){
                            $("#add-layer").modal('hide');
                            alert('Layer will be fetched in the background.');
                        }
                    }
                },
                error: function(){
                    alert('Request failed');
                }
            });
            return false;
        });

        $("#add-layer").on('shown.bs.modal', function(){

            $("#add-layer-form input[name=user]").val($("#id_user").val());
            $("#add-layer-form input[name=password]").val($("#id_password").val());
            map.invalidateSize();
            resetExtent();
            $("input[name=extent][value=map]").change();
        });
        $("#add-layer").modal('show', {backdrop: 'static'});
    });
</script>

templates/geosafe/metasearch/modal/layer_metadata.html
{% load bootstrap_tags %}
{% load staticfiles %}
<div class="modal fade" id="show-metadata" tabindex="-1" role="dialog" aria-labelledby="Layer Metadata">
    <style>
    #show-metadata textarea{
        width: 100%;
        height: 300px;
    }
    </style>
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i class="fa fa-times-circle-o"></i></button>
                    <h4 class="modal-title">
                    <img class="glyphicon" src="{% static 'geosafe/img/inasafe-icon.png' %}" ></img>
                    Layer Metadata
                </h4>
            </div>
            <div class="modal-body">
                <textarea>
                    {{ metadata|safe }}
                </textarea>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function(){
            $("#show-metadata").modal('show', {backdrop: 'static'});
        });
    </script>
</div>