urls.py
__author__ = 'ismailsunni'

from django.conf.urls import patterns, url

from geosafe.views import metasearch
from geosafe.views.analysis import (
    AnalysisListView,
    AnalysisCreateView,
    AnalysisDetailView,
    layer_tiles,
    layer_metadata,
    layer_keywords,
    layer_archive,
    layer_list, rerun_analysis,
    analysis_json, toggle_analysis_saved, download_report, layer_panel,
    analysis_summary, cancel_analysis, validate_analysis_extent,
    impact_json, layer_geojson)

urlpatterns = patterns(
    '',
    url(
        r'^analysis/create(?:/(?P<pk>\d*))?$',
        AnalysisCreateView.as_view(),
        name='analysis-create'
    ),
    url(
        r'^analysis/(?:/user/(?P<user>\d*))?$',
        AnalysisListView.as_view(),
        name='analysis-list'
    ),
    url(
        r'^analysis/(?P<pk>\d+)$',
        AnalysisDetailView.as_view(),
        name='analysis-detail'
    ),
    url(
        r'^analysis/layer-geojson$',
        layer_geojson,
        name='layer-geojson'
    ),
    url(
        r'^analysis/layer-tiles$',
        layer_tiles,
        name='layer-tiles'
    ),
    url(
        r'^analysis/layer-metadata/(?P<layer_id>\d+)',
        layer_metadata,
        name='layer-metadata'
    ),
    url(
        r'^analysis/layer-keywords$',
        layer_keywords,
        name='layer-keywords'
    ),
    url(
        r'^analysis/layer-archive/(?P<layer_id>\d+)',
        layer_archive,
        name='layer-archive'
    ),
    url(
        r'^analysis/layer-list/'
        r'(?P<layer_purpose>(hazard|exposure|aggregation|impact))'
        r'(?:/(?P<layer_category>\w*))?'
        r'(?:/(?P<bbox>[,.\d-]*))?',
        layer_list,
        name='layer-list'
    ),
    url(
        r'^analysis/layer-panel'
        r'(?:/(?P<bbox>[\[\] ,.\d-]*))?',
        layer_panel,
        name='layer-panel'
    ),
    url(
        r'^analysis/extent/validation/',
        validate_analysis_extent,
        name='validate-analysis-extent'
    ),
    url(
        r'^analysis/extent/calculate/',
        validate_analysis_extent,
        name='calculate-area'
    ),
    url(
        r'^analysis/rerun/'
        r'(?P<analysis_id>\d+)',
        rerun_analysis,
        name='rerun-analysis'
    ),
    url(
        r'^analysis/cancel/'
        r'(?P<analysis_id>\d+)',
        cancel_analysis,
        name='cancel-analysis'
    ),
    url(
        r'^analysis/check/'
        r'(?P<analysis_id>\d+)',
        analysis_json,
        name='check-analysis'
    ),
    url(
        r'^analysis/check-impact/'
        r'(?P<impact_id>[-\d]+)',
        impact_json,
        name='check-impact'
    ),
    url(
        r'^analysis/toggle-saved/'
        r'(?P<analysis_id>[-\d]+)',
        toggle_analysis_saved,
        name='toggle-analysis-saved'
    ),
    url(
        r'^analysis/report/'
        r'(?P<analysis_id>[-\d]+)/'
        r'(?P<data_type>(map|table|reports|all))',
        download_report,
        name='download-report'
    ),
    url(
        r'^analysis/summary/'
        r'(?P<impact_id>[-\d]+)/',
        analysis_summary,
        name='analysis-summary'
    ),

    # Metasearch
    url(
        r'^metasearch/$',
        metasearch.index,
        name='metasearch'
    ),
    url(
        r'^metasearch/csw_ajax$',
        metasearch.csw_ajax,
        name='metasearch_csw_ajax'
    ),
    url(
        r'^metasearch/add_layer$',
        metasearch.add_layer,
        name='metasearch_add_layer'
    ),
    url(
        r'^metasearch/add_layer_dialog',
        metasearch.show_add_layer_dialog,
        name='metasearch_add_layer_dialog'
    ),
    url(
        r'^metasearch/show_metadata',
        metasearch.show_metadata,
        name='metasearch_show_metadata'
    ),

    url(
        r'^metasearch/wfs_proxy',
        metasearch.wfs_proxy,
        name='metasearch_wfs_proxy'
    ),
)

models.py
from __future__ import absolute_import

import json
import os
import urlparse
from datetime import datetime

from celery.result import AsyncResult
from django.contrib.gis.geos import GEOSGeometry
from django.core.files.base import File
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext as _
from geonode.utils import bbox_to_wkt

from geonode.layers.models import Layer
from geosafe.app_settings import settings

# flat xpath for the keyword container tag
from geosafe.helpers.suggestions.error_suggestions import AnalysisError

ISO_METADATA_INASAFE_KEYWORD_TAG = (
    '//gmd:supplementalInformation/inasafe')
ISO_METADATA_INASAFE_PROVENANCE_KEYWORD_TAG = (
    '//gmd:supplementalInformation/inasafe_provenance')

ISO_METADATA_NAMESPACES = {
    'gmd': 'http://www.isotc211.org/2005/gmd',
    'gco': 'http://www.isotc211.org/2005/gco'
}


class GeoSAFEException(BaseException):
    pass


class MetadataManager(models.Manager):

    def get_queryset(self):
        """Defer text fields"""
        return super(MetadataManager, self).get_queryset().defer(
            'keywords_xml', 'keywords_json')


# Create your models here.
class Metadata(models.Model):
    """Represent metadata for a layer."""
    layer = models.OneToOneField(
        Layer, primary_key=True, related_name='inasafe_metadata')
    layer_purpose = models.CharField(
        verbose_name='Purpose of the Layer',
        max_length=20,
        blank=True,
        null=True,
        default=''
    )
    category = models.CharField(
        verbose_name='The category of layer purpose that describes a kind of'
                     'hazard or exposure this layer is',
        max_length=30,
        blank=True,
        null=True,
        default=''
    )
    keywords_xml = models.TextField(
        verbose_name='Full representation of InaSAFE keywords in xml format',
        blank=True,
        null=True,
        default=''
    )
    keywords_json = models.TextField(
        verbose_name='Full representation of InaSAFE keywords in json format',
        blank=True,
        null=True,
        default='{}'
    )

    objects = MetadataManager()

    @property
    def keywords(self):
        """Return InaSAFE keywords dict."""
        try:
            return json.loads(self.keywords_json)
        except ValueError:
            return {}

    def reset_metadata(self):
        """Reset to empty metadata."""
        Metadata.objects.filter(pk=self.pk).update(
            keywords_xml='',
            keywords_json='',
            layer_purpose='',
            category='')


class Analysis(models.Model):
    """Represent GeoSAFE analysis"""
    HAZARD_EXPOSURE_CURRENT_VIEW_CODE = 1
    HAZARD_EXPOSURE_CODE = 2
    HAZARD_EXPOSURE_BBOX_CODE = 3

    HAZARD_EXPOSURE_CURRENT_VIEW_TEXT = (
        'Use intersection of hazard, exposure, and current view extent')
    HAZARD_EXPOSURE_TEXT = 'Use intersection of hazard and exposure'
    HAZARD_EXPOSURE_BBOX_TEXT = (
        'Use intersection of hazard, exposure, and bounding box')

    EXTENT_CHOICES = (
        (HAZARD_EXPOSURE_CURRENT_VIEW_CODE, HAZARD_EXPOSURE_CURRENT_VIEW_TEXT),
        (HAZARD_EXPOSURE_CODE, HAZARD_EXPOSURE_TEXT),
        # Disable for now
        # (HAZARD_EXPOSURE_BBOX_CODE, HAZARD_EXPOSURE_BBOX_TEXT),
    )

    class Meta:
        verbose_name_plural = 'Analyses'

    user_title = models.CharField(
        max_length=255,
        verbose_name='User defined title for analysis',
        help_text='Title to assign after analysis is generated.',
        blank=True,
        null=True,
    )
    user_extent = models.CharField(
        max_length=255,
        verbose_name='Analysis extent',
        help_text='User defined BBOX for analysis extent',
        blank=True,
        null=True,
    )
    exposure_layer = models.ForeignKey(
        Layer,
        verbose_name='Exposure Layer',
        help_text='Exposure layer for analysis.',
        blank=False,
        null=True,
        related_name='exposure_layer',
        on_delete=models.SET_NULL
    )
    hazard_layer = models.ForeignKey(
        Layer,
        verbose_name='Hazard Layer',
        help_text='Hazard layer for analysis.',
        blank=False,
        null=True,
        related_name='hazard_layer',
        on_delete=models.SET_NULL
    )
    aggregation_layer = models.ForeignKey(
        Layer,
        verbose_name='Aggregation Layer',
        help_text='Aggregation layer for analysis.',
        blank=True,
        null=True,
        related_name='aggregation_layer',
        on_delete=models.SET_NULL
    )
    aggregation_filter = models.TextField(
        verbose_name='Serialized JSON of selected aggregation area name',
        help_text='List of aggregation area being used in aggregation layer',
        blank=True,
        null=True,
    )
    filtered_aggregation = models.CharField(
        max_length=255,
        verbose_name='Temporary file location of filtered aggregation',
        blank=True,
        null=True
    )
    impact_function_id = models.CharField(
        max_length=100,
        verbose_name='ID of Impact Function',
        help_text='The ID of Impact Function used in the analysis.',
        blank=True,
        null=True
    )
    extent_option = models.IntegerField(
        choices=EXTENT_CHOICES,
        default=HAZARD_EXPOSURE_CODE,
        verbose_name='Analysis extent',
        help_text='Extent option for analysis.'
    )

    impact_layer = models.ForeignKey(
        Layer,
        verbose_name='Impact Layer',
        help_text='Impact layer from this analysis.',
        blank=True,
        null=True,
        related_name='impact_layer'
    )

    task_id = models.CharField(
        max_length=40,
        verbose_name='Task UUID',
        help_text='Task UUID that runs analysis',
        blank=True,
        null=True
    )

    task_state = models.CharField(
        max_length=10,
        verbose_name='Task State',
        help_text='Task State recorded in the model',
        blank=True,
        null=True
    )

    keep = models.BooleanField(
        verbose_name='Keep impact result',
        help_text='True if the impact will be kept',
        blank=True,
        default=False,
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='Author',
        help_text='The author of the analysis',
        blank=True,
        null=True
    )

    report_map = models.FileField(
        verbose_name='Report Map',
        help_text='The map report of the analysis',
        blank=True,
        null=True,
        upload_to='analysis/report/'
    )

    report_table = models.FileField(
        verbose_name='Report Table',
        help_text='The table report of the analysis',
        blank=True,
        null=True,
        upload_to='analysis/report/'
    )

    start_time = models.DateTimeField(
        default=datetime.now
    )

    end_time = models.DateTimeField(
        default=datetime.now
    )

    language_code = models.CharField(
        max_length=10,
        verbose_name='Language Code',
        help_text='Language being used by the django app',
        default='en'
    )

    def assign_report_map(self, filename):
        try:
            self.report_map.delete()
        except BaseException:
            pass
        self.report_map = File(open(filename))

    def assign_report_table(self, filename):
        try:
            self.report_table.delete()
        except BaseException:
            pass
        self.report_table = File(open(filename))

    def get_task_result(self):
        """
        :return: celery AsyncResult
        :rtype: celery.result.AsyncResult
        """
        return AsyncResult(self.task_id)

    def user_extent_bbox(self):
        """Return user extent as BBOX array.

        Format: [[left,top], [right, bottom]]
        """
        bbox_arr = self.user_extent.split(',')
        bbox_float = [float(i) for i in bbox_arr]
        return [[bbox_float[0], bbox_float[1]],
                [bbox_float[2], bbox_float[3]]]

    def user_extent_area(self):
        """Return user extent area in meter square."""
        bbox_float = self.user_extent_bbox()
        extent_geom = GEOSGeometry(
            bbox_to_wkt(
                bbox_float[0][0], bbox_float[1][0],
                bbox_float[0][1], bbox_float[1][1]), srid=4326)
        # Check the size of the extent
        # convert to EPSG:3410 for equal area projection
        extent_geom.transform('3410')
        # Return in km^2
        return extent_geom.area / 1000000

    def get_label_class(self):
        state = self.get_task_state()
        if state == 'SUCCESS':
            return 'success'
        elif state == 'FAILURE':
            return 'danger'
        else:
            return 'info'

    def get_task_state(self):
        """Check task state

        State need to be evaluated from task result.
        However after a certain time, the task result is removed from broker.
        In this case, the state will always return 'PENDING'. For this, we
        receive the actual result from self.state, which is the cached state

        :return: task state string
        :rtype: str
        """
        result = self.get_task_result()
        if not result.task_id:
            # If no task_id, we don't have any task yet.
            return 'FAILURE'
        # chain state, iterate result
        if result.children:
            for child in result.children:
                try:
                    if child.state == 'PENDING':
                        return self.task_state
                    else:
                        return child.state
                except BaseException:
                    return 'FAILURE'
        # If state result is not PENDING, this could be the current state
        if result.state != 'PENDING':
            return result.state

        # If state result is PENDING, it is possible the result is gone.

templates/geosafe/analysis/create.html
{% extends 'geosafe/analysis/create_base.html' %}

templates/geosafe/analysis/detail.html
{% extends 'geosafe/analysis/detail_base.html' %}

templates/geosafe/analysis/legend.html
{% extends 'geosafe/analysis/legend_base.html' %}

templates/geosafe/analysis/legend_base.html
{% load i18n %}
{% block legend %}
    <div class="legend">
        <div id="legend-title">
            <a href="#" style="font-style: oblique; text-align: center;"><p>{% trans "Legend" %}</p></a>
        </div>
        <div id="legend-body">
            <div id="legend-hazard-body">
                <p>{% trans "Hazard:" %} <span id="legend-hazard-name"></span></p>
                <p><input class="transparency-slider" type="text" value="5" id="hazard-slider" data-slider-min="1"
                          data-slider-max="10"
                          data-slider-step="1" onchange="set_transparency();"></p>
                <p><img id="hazard-legend-img"/></p>
            </div>
            <div id="legend-exposure-body">
                <p>{% trans "Exposure:"%} <span id="legend-exposure-name"></span></p>
                <p><input class="transparency-slider" type="text" value="5" id="exposure-slider" data-slider-min="1"
                          data-slider-max="10"
                          data-slider-step="1" onchange="set_transparency();"></p>
                <p><img id="exposure-legend-img"/></p>
            </div>
            <div id="legend-aggregation-body">
                <p>{% trans "Aggregation:" %} <span id="legend-aggregation-name"></span></p>
                <p><input class="transparency-slider" type="text" value="5" id="aggregation-slider" data-slider-min="1"
                          data-slider-max="10"
                          data-slider-step="1" onchange="set_transparency();"></p>
                <p><img id="aggregation-legend-img"/></p>
            </div>
            <div id="legend-impact-body">
                <p>{% trans "Impact:" %} <span id="legend-impact-name"></span></p>
                <p><input class="transparency-slider" type="text" value="5" id="impact-slider" data-slider-min="1"
                          data-slider-max="10"
                          data-slider-step="1" onchange="set_transparency();"></p>
                <p><img id="impact-legend-img"/></p>
            </div>
        </div>
    </div>
{% endblock legend %}

templates/geosafe/analysis/list.html
{% extends 'geosafe/analysis/list_base.html' %}

templates/geosafe/analysis/list_base.html
{% extends 'geonode_base.html' %}
{% load staticfiles %}
{% load i18n %}
{% block extra_head %}
    <link rel="stylesheet" href="{% static 'geosafe/css/main.css' %}" />
    <link rel="stylesheet" href="{% static 'geosafe/css/jquery.dynatable.css' %}" />
{% endblock %}
{% block body %}
    <style>
        .btn .fa-check{
            display: none;
        }
        .btn.active .fa-check{
            display: inline-block;
            color: #50cf5c;
        }
        .btn .fa-close{
            display: inline-block;
            color: #f15a2b;
        }
        .btn.active .fa-close{
            display: none;
        }
        .btn.processing .fa-close{
            display: none;
        }
        .btn .fa-spinner{
            display: none;
        }
        .btn.processing .fa-spinner{
            display: inline-block;
        }

        .save-analysis.processing .onoffswitch-inner,
        .save-analysis.processing .onoffswitch-switch{
            display: none;
        }
        .save-analysis.processing{
            width: auto;
        }
        .save-analysis.processing .processing-indicator{
            display: inline-block;
            white-space: nowrap;
            height: 30px;
            padding-left: 10px;
            padding-right: 10px;
            padding-top: 5px;
        }
        .save-analysis .processing-indicator{
            display: none;
        }

        #user-filter-group{
            margin-right: 10px;
        }

        .download-link{
            white-space: nowrap;
        }
    </style>
    <h1>{% trans "List of Analysis" %}</h1>
    <div>
        {% if analysis_list %}
            <div id="user-filter-group" class="btn-group" data-toggle="buttons">
                <label class="btn btn-primary active">
                    <input type="radio" name="user-filter" checked value="all">
                    {% trans "All" %}
                </label>
                <label class="btn btn-primary">
                    <input type="radio" name="user-filter" value="user">
                    {% if not user.username %}
                        {% trans "Anonymous" %}
                    {% else %}
                        {% trans "Current users" %}
                    {% endif %}
                </label>
            </div>
            <table id="analysis-list" class="table table-striped">
                <thead>
                <tr>
                    <th>{% trans "User" %}</th>
                    <th>{% trans "Date Created" %}</th>
{#                    <th>Exposure</th>#}
{#                    <th>Hazard</th>#}
{#                    <th>Aggregation</th>#}
{#                    <th>Extent</th>#}
{#                    <th>{% trans "Impact Function Name" %}</th>#}
                    <th>{% trans "Impact Result" %}</th>
                    <th>{% trans "View" %}</th>
                    {% if user.username %}
                        <th>{% trans "Save" %}</th>
                    {% endif %}
                    <th>{% trans "Download" %}</th>
                    <th>{% trans "Analysis Detail" %}</th>
                </tr>
                </thead>
                <tbody>
                {% for analysis in analysis_list %}
                    <tr>
                        <td>
                            <a href="{{ analysis.user.get_absolute_url }}">{{ analysis.user.username }}</a>
                        </td>
                        <td>
                            {% if analysis.impact_layer %}
                                {{ analysis.impact_layer.date }}
                            {% else %}
                                {% trans "Result not yet created" %}
                            {% endif %}
                        </td>
{#                        <td>#}
{#                            <a href="{% url 'layer_detail' layername=analysis.exposure_layer.typename %}">{{ analysis.exposure_layer }}</a>#}
{#                        </td>#}
{#                        <td>#}
{#                            <a href="{% url 'layer_detail' layername=analysis.hazard_layer.typename %}">{{ analysis.hazard_layer }}</a>#}
{#                        </td>#}
{#                        <td>#}
{#                            <a href="{% url 'layer_detail' layername=analysis.aggregation_layer.typename %}">{{ analysis.aggregation_layer }}</a>#}
{#                        </td>#}
{#                        <td>#}
{#                            {{ analysis.get_extent_option_display }}#}
{#                        </td>#}
{#                        <td>#}
{#                            {{ analysis.impact_function_name }}#}
{#                        </td>#}
                        <td>
                            {% if not analysis.get_task_result %}
                                {% trans "Analysis not yet running" %}
                            {% elif analysis.get_task_state == 'SUCCESS' %}
                                <a href="{% url 'layer_detail' layername=analysis.impact_layer.alternate %}"> {{ analysis.impact_layer }} <br /> {% trans "Duration:" %} {{ analysis.start_time|timesince:analysis.end_time }} </a>
                            {% else %}
                                <div>{% trans "Task Status:" %} <span class="label label-{{ analysis.get_label_class }}">{{ analysis.get_task_state }}</span></div>
                                        {{ analysis.hazard_layer }} on {{ analysis.exposure_layer }} <br />{% trans "Start Time:" %} {{ analysis.start_time }}
                                {% if analysis.get_task_state == 'FAILURE' %}
                                <div>
                                    <form action="{% url 'geosafe:rerun-analysis' analysis_id=analysis.id %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" id="analysis_id" value="{{ analysis.id }}" />
                                        <button type="submit" class="btn btn-primary">{% trans "Rerun Analysis" %}</button>
                                    </form>
                                </div>
                                {% elif not analysis.get_task_state == 'SUCCESS' and user.is_superuser %}
                                <div>
                                    <form action="{% url 'geosafe:cancel-analysis' analysis_id=analysis.id %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" id="analysis_id" value="{{ analysis.id }}" />
                                        <button type="submit" class="btn btn-primary">{% trans "Cancel Analysis" %}</button>
                                    </form>
                                </div>
                                {% endif %}
                            {% endif %}
                        </td>
                        <td>
                            <div>
                                <a class="download-link" href="{% url 'geosafe:analysis-create' pk=analysis.id %}">{% trans "Analysis Page" %}</a>
                            </div>
                            {% if analysis.report_map %}
                                <div>
                                    <a class="download-link" href="{% url 'geosafe:download-report' analysis_id=analysis.id data_type='map' %}" target="_blank">{% trans "Map Report" %}</a>
                                </div>
                            {% endif %}
                            {% if analysis.report_table %}
                                <div>
                                    <a class="download-link" href="{% url 'geosafe:download-report' analysis_id=analysis.id data_type='table' %}" target="_blank">{% trans "Table Report" %}</a>
                                </div>
                            {% endif %}
                        </td>
                        {% if user.username %}
                        <td>
                            <div class="onoffswitch save-analysis">
                                <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox"
                                       id="save_analysis_{{ analysis.id }}"
                                       {% if analysis.keep %}checked{% endif %}
                                       data-id="{{ analysis.id }}">
                                <label class="onoffswitch-label" for="save_analysis_{{ analysis.id }}">
                                    <span class="processing-indicator">
                                        <i class="fa fa-spinner fa-spin"></i>
                                        {% trans "PROCESSING" %}
                                    </span>
                                    <span class="onoffswitch-inner"></span>
                                    <span class="onoffswitch-switch"></span>
                                </label>
                            </div>
                        </td>
                        {% endif %}
                        <td>
                            {% if analysis.impact_layer %}
                                <a href="{% url 'geosafe:download-report' analysis_id=analysis.id data_type='all' %}">{% trans "Download" %}</a>
                            {% else %}
                                {% trans "Result not yet created" %}
                            {% endif %}
                        </td>
                        <td>
                            <a href="{% url 'geosafe:analysis-detail' pk=analysis.pk %}">
                                {% trans "Diagnostic page" %}
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>{% trans "No analysis yet." %}
                <a href="{% url "geosafe:analysis-create" %}">{% trans "Why not create one?" %}</a>
            </p>
        {% endif %}
    </div>
{% endblock %}

{% block extra_script %}
<script type="text/javascript" src="{% static 'geosafe/js/jquery.dynatable.js' %}">
</script>
<script type="text/javascript" src="{% static 'geosafe/js/analysis.js' %}"></script>
<script type="text/javascript">

$(document).ready(function(){

    var analysis_list_dynatable = $("#analysis-list")
            .bind('dynatable:init', function (e, dynatable) {
                dynatable.queries.functions['user'] = function(record, queryValue){
                    return $(record['user']).text() == queryValue;
                }
            }).dynatable().data('dynatable');

    $(".save-analysis input").change(function(){
        var id=$(this).attr('data-id');
        var urlpattern = '{% url "geosafe:toggle-analysis-saved" analysis_id=-1 %}';
        toggle_analysis_saved(urlpattern, id);
    });

    $("#user-filter-group label").on('click', function () {
        if($(this).find('input').val()=='all'){
            analysis_list_dynatable.queries.remove('user');
        }
        else{
            {% if user.username %}
                analysis_list_dynatable.queries.add('user', '{{ user.username }}');
            {% else %}
                analysis_list_dynatable.queries.add('user', 'AnonymousUser');
            {% endif %}
        }
        analysis_list_dynatable.process();
    });
});
</script>
{% endblock %}

templates/geosafe/analysis/options_panel.html
{% extends 'geosafe/analysis/options_panel_base.html' %}